remote_theme: mmistakes/minimal-mistakes
title: "AISYN0O's Blog"
description: Welcome to my blog where I share my thoughts, projects, and experiences!
author:
  name: "AISYN0O's Blog"
  bio: A passionate learner and writer sharing insights on tech, life, and more.
locale: en-US  # Set language to English
search: true  # Enable search feature
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AISYN0O"
header:
  pages:
    - title: About
      url: /about/
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue-term: "pathname"
seo:
  date_modified: true
  author: "AISYN0O"
